accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.redirect_to_login),
    path("login/", views.LoginView.as_view(), name="login"),
    path("join/", views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("", include("django.contrib.auth.urls")),
]

purchaseRequests/urls.py
from django.urls import path
from . import views

app_name = "purchaseRequests"
urlpatterns = [
    path("", views.list, name="list"),
    path("export/", views.export, name="export"),
    path("summary/", views.summary, name="summary"),
    path("new/", views.new_request, name="new"),
    path("<int:pReq_id>", views.detail, name="detail"),
    path("<int:pReq_id>/change-status", views.change_preq_status, name="change_preq_status"),
    path("<int:pReq_id>/edit", views.edit, name="edit"),
    path("<int:pReq_id>/delete-request", views.delete_request, name="delete_request"),
]

team_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path("purchase-requests/", include("purchaseRequests.urls")),
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

purchaseRequests/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from tldextract import extract


class Request(models.Model):
    timestamp = models.DateTimeField()
    author = models.ForeignKey(User, null=True, related_name="+", on_delete=models.SET_NULL)
    item = models.CharField(max_length=75)
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveSmallIntegerField()
    link = models.URLField(max_length=2000)
    supplier = models.CharField(max_length=40, null=True)
    notes = models.TextField(null=True, blank=True)

    approved = models.NullBooleanField()
    approved_timestamp = models.DateTimeField(null=True, blank=True)
    approver = models.ForeignKey(User, null=True, blank=True, related_name="+", on_delete=models.SET_NULL)

    ordered = models.BooleanField(default=False)
    order_timestamp  = models.DateTimeField(null=True, blank=True)
    orderer = models.ForeignKey(User, null=True, blank=True, related_name="+", on_delete=models.SET_NULL)
    shipping_cost = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    delivered = models.BooleanField(default=False)
    delivery_timestamp = models.DateTimeField(null=True, blank=True)
    delivery_person = models.ForeignKey(User, null=True, blank=True, related_name="+", on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if not self.supplier:
            self.supplier = extract(self.link).domain
        super(Request, self).save(*args, **kwargs)

    def __str__(self):
        return self.item + ", x" + str(self.quantity)

    def line_total(self):
        if self.shipping_cost:
            return self.shipping_cost + (self.quantity) * (self.cost)
        else:
            return self.quantity * self.cost

purchaseRequests/views.py
from purchaseRequests import email_config
from team_manager import settings
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector
from django.db.models import Q, F, Sum, DecimalField
from .models import Request
import csv
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pytz


class HttpResponseSeeOther(HttpResponseRedirect):
    status_code = 303


def validate_date_input(date_str, in_format="%m/%d/%Y"):
    try:
        datetime.strptime(date_str, in_format)
        return True
    except ValueError:
        return False


def gen_dt_bin_data(raw_data, bin_start, bin_end):
    bin_reqs = raw_data.filter(timestamp__gte=bin_start, timestamp__lt=bin_end)
    bin_apps = raw_data.filter(approved_timestamp__gte=bin_start, approved_timestamp__lt=bin_end)
    bin_ords = raw_data.filter(order_timestamp__gte=bin_start, order_timestamp__lt=bin_end)
    bin_dels = raw_data.filter(delivery_timestamp__gte=bin_start, delivery_timestamp__lt=bin_end)

    return {'t': bin_start.strftime("%Y-%m-%d %H:%M"),
            'y': bin_reqs.count() + bin_apps.count() + bin_ords.count() + bin_dels.count()},\
           {'t': bin_start.strftime("%Y-%m-%d %H:%M"),
            'y': float(bin_ords.aggregate(t=Sum(F('cost') * F('quantity'), output_field=DecimalField()))["t"] or 0.00) +
                 float(bin_ords.exclude(shipping_cost__isnull=True).aggregate(sc=Sum('shipping_cost'))["sc"] or 0.00)}


@login_required
def list(request):
    pur_reqs = Request.objects.all()

    in_format = "%m/%d/%Y"
    db_format = "%Y-%m-%d"

    # Date filters
    if "start" in request.GET and validate_date_input(request.GET["start"]):
        st = datetime.strptime(request.GET["start"], in_format)
        st = st.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime(db_format)
        pur_reqs = pur_reqs.filter(timestamp__gte=st)

    if "end" in request.GET and validate_date_input(request.GET["end"]):
        et = datetime.strptime(request.GET["end"], in_format)
        et += timedelta(days=1)
        et = et.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime(db_format)
        pur_reqs = pur_reqs.filter(timestamp__lt=et)

    # Approval filters
    final_query = Q()
    if "den" in request.GET:
        final_query |= Q(approved=False)
    if "und" in request.GET:
        final_query |= Q(approved=None)
    if "app" in request.GET:
        final_query |= Q(approved=True, ordered=False, delivered=False)
    if "ord" in request.GET:
        final_query |= Q(ordered=True, delivered=False)
    if "del" in request.GET:
        final_query |= Q(delivered=True)

    pur_reqs = pur_reqs.filter(final_query)

    # Search bar
    if "q" in request.GET and request.GET["q"]:
        search_terms = request.GET["q"].split()

        product_terms = []
        user_terms = []
        supplier_terms = []
        for term in search_terms:
            if term.startswith("user:"):
                user_terms.append(term[5:])
            elif term.startswith("supp:"):
                supplier_terms.append(term[5:])
            elif term.startswith("supplier:"):
                supplier_terms.append(term[9:])
            else:
                product_terms.append(term)

        for p_term in product_terms:
            pur_reqs = pur_reqs.annotate(
                search=SearchVector("item")
            ).filter(search=p_term)

        user_or_query = Q()
        for u_term in user_terms:
            user_or_query |= Q(author__username=u_term)
        pur_reqs = pur_reqs.filter(user_or_query)

        supp_or_query = Q()
        for supp_term in supplier_terms:
            supp_or_query |= Q(supplier__icontains=supp_term)
        pur_reqs = pur_reqs.filter(supp_or_query)


    submitted_filters = {
        "start": request.GET["start"] if "start" in request.GET and validate_date_input(request.GET["start"]) else "",
        "end": request.GET["end"] if "end" in request.GET and validate_date_input(request.GET["end"]) else "",
        "q": request.GET["q"] if "q" in request.GET else "",
        "app_checked": "app" in request.GET,
        "und_checked": "und" in request.GET,
        "den_checked": "den" in request.GET,
        "ord_checked": "ord" in request.GET,
        "del_checked": "del" in request.GET,
    }

    context = {
        'pur_req_list': pur_reqs.order_by('-timestamp'),
        'filters': submitted_filters,
        'theme_color': settings.THEME_COLOR,
        'team_name': settings.TEAM_NAME,
    }
    return render(request, "purchaseRequests/list.html", context)


@login_required
def export(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="purchase_requests.csv"'

    writer = csv.writer(response)
    writer.writerow(['id', 'date', 'time', 'author', 'price per unit', 'quantity', 'total cost (w/o shipping)', 'link',
                     'approved?', 'approver', 'approval time',
                     'purchased?', 'purchaser', 'purchase time', 'shipping cost',
                     'delivered?', 'delivery signee', 'delivery time'])

    for pur_req in Request.objects.all().order_by('-timestamp').values():
        timestamp = pur_req['timestamp'].astimezone(pytz.timezone(settings.TIME_ZONE))
        writer.writerow([
            pur_req['id'],
            timestamp.strftime("%b %d, %Y"),
            timestamp.strftime("%H:%M"),
            User.objects.get(pk=pur_req['author_id']).get_username(),
            pur_req['cost'],
            pur_req['quantity'],
            pur_req['cost'] * pur_req['quantity'],
            pur_req['link'],
            pur_req['approved'],
            User.objects.get(pk=pur_req['approver_id']).get_username() if pur_req['approver_id'] is not None else "",
            pur_req['approved_timestamp'],
            pur_req['ordered'],
            User.objects.get(pk=pur_req['orderer_id']).get_username() if pur_req['orderer_id'] is not None else "",
            pur_req['order_timestamp'],
            pur_req['shipping_cost'],
            pur_req['delivered'],
            User.objects.get(pk=pur_req['delivery_person_id']).get_username() if pur_req['delivery_person_id']
                                                                                 is not None else "",
            pur_req['delivery_timestamp'],
        ])

    return response


def summary(request):
    pur_reqs = Request.objects.all()
    in_format = "%b %d, %Y"
    db_format = "%Y-%m-%d"

    earliest_req_time = pur_reqs.earliest('timestamp').timestamp
    # Date filtering
    if "dr" in request.GET and " - " in request.GET["dr"]:
        st, et = request.GET["dr"].split(" - ")
        if validate_date_input(st, in_format) and validate_date_input(et, in_format):
            st = datetime.strptime(st, in_format)
            et = datetime.strptime(et, in_format) + timedelta(days=1)

            start_time = st
            end_time = et

            st = st.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime(db_format)
            et = et.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime(db_format)

            pur_reqs = pur_reqs.filter((Q(timestamp__gte=st) | Q(approved_timestamp__gte=st) |
                                        Q(order_timestamp__gte=st) | Q(delivery_timestamp__gte=st)) &
                                       (Q(timestamp__lte=et) | Q(approved_timestamp__lte=et) |
                                        Q(order_timestamp__lte=et) | Q(delivery_timestamp__lte=et)))
        else:
            start_time = earliest_req_time
            end_time = timezone.now()
    else:
        start_time = earliest_req_time
        end_time = timezone.now()


    # Data generation for the chart
    activity = []
    spending = []

    range_width = end_time - start_time
    print(range_width)
    if range_width <= timedelta(days=1):
        interval = "hour"
        tt_format = "h:mm a"
        start_time = datetime(start_time.year, start_time.month, start_time.day, hour=start_time.hour, minute=0,
                              second=0, microsecond=0, tzinfo=start_time.tzinfo)
        round_up = 0 if end_time.minute == 0 and end_time.second == 0 and end_time.microsecond == 0 else 1
        end_time = datetime(end_time.year, end_time.month, end_time.day, hour=end_time.hour + round_up, minute=0,
                            second=0, microsecond=0, tzinfo=end_time.tzinfo)

        range_width = end_time - start_time
        num_bins = int((range_width.days * 86400 + range_width.seconds) / 3600)
    elif range_width <= timedelta(days=6):
        interval = "day"
        tt_format = "M/D h:mm a"
        num_days = range_width.days

        start_time = datetime(start_time.year, start_time.month, start_time.day,
                              hour=int(start_time.hour/num_days)*num_days, minute=0, second=0, microsecond=0,
                              tzinfo=start_time.tzinfo)
        round_up = 0 if end_time.minute == 0 and end_time.second == 0 and end_time.microsecond == 0 else num_days
        end_time = datetime(end_time.year, end_time.month, end_time.day,
                            hour=int(end_time.hour/num_days)*num_days + round_up, minute=0, second=0, microsecond=0,
                            tzinfo=end_time.tzinfo)

        range_width = end_time - start_time
        num_bins = int((range_width.days * 86400 + range_width.seconds) / (3600 * num_days))
    elif range_width <= timedelta(weeks=3):
        interval = "day"
        tt_format = "M/D"
        start_time = datetime(start_time.year, start_time.month, start_time.day, tzinfo=start_time.tzinfo)

purchaseRequests/templates/purchaseRequests/detail.html
{% extends './base.html' %}
{% load staticfiles %}


{% block title %}Purchase Request for {{ pur_req.item }}{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'purchaseRequests/css/detail.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous">

    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'purchaseRequests/js/detail.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="detail-div">
        {% if pur_req.approved is not True and pur_req.approved is not False %}
            {% if pur_req.author == user or user.is_superuser %}
            <a id="edit-button" href="{% url 'purchaseRequests:edit' pur_req.id %}">Edit</a>
            {% endif %}
        {% endif %}

        <h1 id="item-title">{{ pur_req.item }}</h1>
        <ul>
            <li>Cost: ${{ pur_req.cost }} x {{ pur_req.quantity }}{% if pur_req.shipping_cost %} + ${{pur_req.shipping_cost}}{% endif %} = ${{ pur_req.line_total }}</li>
            <li>Time Added: {{ pur_req.timestamp }}</li>
            <li>Requester: {{ pur_req.author.username }}</li>
            <li id="link"><a href="{{ pur_req.link }}">{{ pur_req.link }}</a></li>
        </ul>
        {% if pur_req.notes %}
        <div id="notes-div">
            <div class="accordion">
                <hr>
                <button id="acc-button">Notes <i id="arrow" class="fas fa-angle-down"></i></button>
            </div>
            <span id="note-span" style="display: none;">{{ pur_req.notes }}</span>
        </div>
        {% endif %}

        {% if pur_req.approved is not True and pur_req.approved is not False %}
        <form id="approval-states-container" class="tab-content" method="post"
              action="{% url 'purchaseRequests:detail' pur_req.id %}">
            {% csrf_token %}
            <table id="approval-states-table">
                <tr>
                    <td id="td-approved" class="{{ state.2 }} {{ selectable }}">
                        <button class="approval-button" type="submit" name="app-but"
                                form="approval-states-container" {{ disable_buttons }}>
                            <i class="fas fa-check"></i>
                        </button>
                    </td>
                    <td id="td-undecided" class="{{ state.1 }} {{ selectable }}">
                        <button class="approval-button" type="submit" name="und-but"
                                form="approval-states-container" {{ disable_buttons }}>
                            <i class="fas fa-question"></i>
                        </button>
                    </td>
                    <td id="td-denied" class="{{ state.0 }} {{ selectable }}">
                        <button class="approval-button" type="submit" name="den-but"
                                form="approval-states-container" {{ disable_buttons }}>
                            <i class="fas fa-times"></i>
                        </button>
                    </td>
                </tr>
            </table>
        </form>
        {% elif pur_req.approved is False %}
        <div id="denied-message" class="tab-content big-message">
            <h1>Denied&ensp;</h1>
            <svg>
                <use xlink:href="#denied-icon"></use>
            </svg>
        </div>
        {% elif pur_req.approved and pur_req.ordered is False %}
        <div id="approved-message" class="tab-content big-message">
            <h1>Approved&ensp;</h1>
            <svg>
                <use xlink:href="#approved-icon"></use>
            </svg>
            {% if is_purchaser %}
            <form id="order-form" method="post" action="{% url 'purchaseRequests:detail' pur_req.id %}">
                {% csrf_token %}
                <div id="ord-inp-div">
                    <label for="shipping-inp">Shipping cost:</label>
                    <div class="input-icon">
                        <input id="shipping-inp" type="number" name="shipping" min="0" max="3654" step="0.01"
                               placeholder="0.00">
                        <i>$</i>
                    </div>
                </div>
                <button id="purchase-sub" class="form-sub" type="submit">
                    <span>Purchase&ensp;</span>
                    <svg class="icon">
                        <use xlink:href="#ordered-icon"></use>
                    </svg>
                </button>
            </form>
            {% endif %}
        </div>
        {% elif pur_req.ordered and pur_req.delivered is False %}
        <div id="purchased-message" class="tab-content big-message">
            <h1>Purchased&ensp;</h1>
            <svg>
                <use xlink:href="#ordered-icon"></use>
            </svg>
            {% if is_purchaser %}
            <form id="delivery-form" method="post" action="{% url 'purchaseRequests:detail' pur_req.id %}">
                {% csrf_token %}
                <input type="checkbox" name="delivered" style="display:none;" checked>
                <button id="deliver-sub" class="form-sub" type="submit">
                    <span>Mark delivered&ensp;</span>
                    <svg class="icon">
                        <use xlink:href="#delivered-icon"></use>
                    </svg>
                </button>
            </form>
            {% endif %}
        </div>
        {% else %}
        <div id="delivered-message" class="tab-content big-message">
            <h1>Delivered&ensp;</h1>
            <svg>
                <use xlink:href="#delivered-icon"></use>
            </svg>
        </div>
        {% endif %}

        <div id="tabs-div">
            <table>
                <tr>
                    <td id="app-tab" class="tab {% if pur_req.approved %}completed-tab
                    {% elif pur_req.approved == False %}denied-tab {% else %}cur-tab {% endif %}">
                        {% if pur_req.approved %}Approved <i class="fas fa-check"></i>
                        {% elif pur_req.approved == False %}Denied <i class="fas fa-times"></i>
                        {% else %}Awaiting approval
                        {% endif %}
                    </td>
                    <td id="ord-tab" class="tab {% if pur_req.ordered %}completed-tab{% endif %}
                    {% if pur_req.approved and pur_req.ordered is not True %}cur-tab {% endif %}">
                        {% if pur_req.ordered %}Purchased <i class="fas fa-check"></i>
                        {% elif pur_req.approved and pur_req.ordered is not True %} Awaiting purchase
                        {% else %}Purchase
                        {% endif %}
                    </td>
                    <td id="del-tab" class="tab {% if pur_req.delivered %}completed-tab{% endif %}
                    {% if pur_req.ordered and pur_req.delivered is not True %}cur-tab {% endif %}">
                        {% if pur_req.delivered %}Delivered <i class="fas fa-check"></i>
                        {% elif pur_req.ordered and pur_req.delivered is not True %}Awaiting delivery
                        {% else %}Delivery{% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

purchaseRequests/templates/purchaseRequests/edit.html
{% extends './base.html' %}
{% load staticfiles %}


{% block title %}Edit{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'purchaseRequests/css/edit.css' %}">
{% endblock %}

{% block content %}
    <div id="content">
        <h1 id="header">Edit Purchase Request</h1>
        <form id="edit-item-form" method="post" action="{% url 'purchaseRequests:edit' pur_req.id %}">
            {% csrf_token %}
            <div class="form-row">
                <label for="item-inp">Item:</label>
                <input id="item-inp" type="text" name="item" maxlength="75" value="{{ pur_req.item }}"
                       required autofocus>
            </div>
            <div class="form-row two-input-row">
                <div id="id-cost-div" class="two-input-row-item">
                    <label for="cost-inp">Cost per unit:</label>
                    <div class="input-icon">
                        <input id="cost-inp" type="number" name="cost" min="0" max="10000" step="0.01"
                               placeholder="0.00" value="{{ pur_req.cost }}" required>
                        <i>$</i>
                    </div>
                </div>

                <div id="id-qty-div" class="two-input-row-item">
                    <label for="qty-inp">Quantity:</label>
                    <input id="qty-inp" type="number" name="quantity" min="1" max="3654" value="{{ pur_req.quantity }}" required>
                </div>
            </div>
            <div class="form-row">
                <label for="url-inp">Link:</label>
                <input id="url-inp" type="url" name="link" value="{{ pur_req.link }}" required>
            </div>
            <div class="form-row">
                <label for="notes-inp">Notes:</label>
                <textarea id="notes-inp" name="notes" maxlength="500">{{ pur_req.notes }}</textarea>
            </div>
            <div class="submit-row form-row">
                <input type="button" id="cancel-button" value="Cancel"
                       onclick="location.href='{% url 'purchaseRequests:detail' pur_req.id %}'">
                <input type="button" id="delete-button" value="Delete"
                       onclick="location.href='{% url 'purchaseRequests:delete_request' pur_req.id %}'">
                <input type="submit" id="save-button" value="Save">
            </div>
        </form>
    </div>
{% endblock %}

purchaseRequests/templates/purchaseRequests/list.html
{% extends './base.html' %}
{% load static %}


{% block title %}{{ team_name }} Purchase Requests{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'purchaseRequests/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'purchaseRequests/css/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'purchaseRequests/css/nav_bar.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous">

    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block content %}
    <div id="content">
        <h1>Purchase Requests for {{ team_name }}</h1>
        <div id="filter-bar">
            <form method="get" action="{% url 'purchaseRequests:list' %}">
                <div id="date-filter" class="filter">
                    <div class="input-icon date-input">
                        <input type="text" name="start" class="datepicker" id="startdate" value="{{ filters.start }}">
                        <i class="far fa-calendar-alt"></i>
                    </div>
                    <div class="input-icon date-input">
                        <input type="text" name="end" class="datepicker"  id="enddate" value="{{ filters.end }}">
                        <i class="far fa-calendar-alt"></i>
                    </div>
                </div>
                <input type="text" name="q" placeholder="Search" value="{{ filters.q }}" id="search-bar" class="filter">
                <div id="approval-filter" class="filter">
                    <table id="approval-states-table">
                        <tr>
                            <td id="td-denied" class="app-cell">
                                <input id="den-but" class="approval-button" type="checkbox" name="den"
                                       {% if filters.den_checked %}checked{% endif %}>
                                <label class="app-label-div" for="den-but">
                                    <i class="fas fa-times"></i>
                                </label>
                            </td>
                            <td id="td-undecided" class="app-cell filt-border">
                                <input id="und-but" class="approval-button" type="checkbox" name="und"
                                       {% if filters.und_checked %}checked{% endif %}>
                                <label class="app-label-div" for="und-but">
                                    <i class="fas fa-question"></i>
                                </label>
                            </td>
                            <td id="td-approved" class="app-cell filt-border">
                                <input id="app-but" class="approval-button" type="checkbox" name="app"
                                       {% if filters.app_checked %}checked{% endif %}>
                                <label class="app-label-div" for="app-but">
                                    <i class="fas fa-check"></i>
                                </label>
                            </td>
                            <td id="td-ordered" class="app-cell filt-border">
                                <input id="ord-but" class="approval-button" type="checkbox" name="ord"
                                       {% if filters.ord_checked %}checked{% endif %}>
                                <label class="app-label-div svg-label" for="ord-but">
                                    <svg class="icon">
                                        <use xlink:href="#ordered-icon"></use>
                                    </svg>
                                </label>
                            </td>
                            <td id="td-delivered" class="app-cell filt-border">
                                <input id="del-but" class="approval-button" type="checkbox" name="del"
                                       {% if filters.del_checked %}checked{% endif %}>
                                <label class="app-label-div svg-label" for="del-but">
                                    <svg class="icon">
                                        <use xlink:href="#delivered-icon"></use>
                                    </svg>
                                </label>
                            </td>
                        </tr>
                    </table>
                </div>
                <input type="submit" value="Apply filters" id="submit-filter" class="filter">
            </form>
            <script type="text/javascript">{% include './calendar.js' %}</script>
        </div>
        <table id="reqlist">
            <thead>
                <tr>
                    <th class="date" style="background-color:{{ theme_color }};">Date</th>
                    <th class="item" style="background-color:{{ theme_color }};">Item</th>
                    <th class="qty" style="background-color:{{ theme_color }};">Quantity</th>
                    <th class="tcost" style="background-color:{{ theme_color }};">Total Cost</th>
                    <th class="link" style="background-color:{{ theme_color }};">Link</th>
                    <th class="status" style="background-color:{{ theme_color }};">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for pur_req in pur_req_list %}
                <tr class="content-row" onclick="location.href = '{% url 'purchaseRequests:detail' pur_req.id %}';">
                    <td class="date">{{ pur_req.timestamp|date:'n/d/y' }}</td>
                    <td class="item">{{ pur_req.item }}</td>
                    <td class="qty">{{ pur_req.quantity }}</td>
                    <td class="tcost">${{ pur_req.line_total }}</td>
                    <td class="link">
                        <a href="{{ pur_req.link }}">{{ pur_req.link }}</a>
                    </td>
                    <td class="status">
                        {% if pur_req.approved %}
                            {% if pur_req.ordered %}
                                {% if pur_req.delivered %}
                                <svg class="icon">
                                    <use xlink:href="#delivered-icon"></use>
                                </svg>
                                {% else %}
                                <svg class="icon">
                                    <use xlink:href="#ordered-icon"></use>
                                </svg>
                                {% endif %}
                            {% else %}
                            <svg class="icon" id="app-svg">
                                <use xlink:href="#approved-icon"></use>
                            </svg>
                            {% endif %}
                        {% elif pur_req.approved == False %}
                        <svg class="icon" id="den-svg">
                            <use xlink:href="#denied-icon"></use>
                        </svg>
                        {% else %}
                        <i class="fas fa-question"></i>
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" id="empty-message">
                        No requests found. Try adjusting the filters to get more results.
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

purchaseRequests/templates/purchaseRequests/nav_bar.html
<header id="navbar">
    <div class="centered-div">
        <a class="navbar-link" href="{% url 'purchaseRequests:list' %}">All requests</a>
        <a class="navbar-link" href="{% url 'purchaseRequests:new' %}">New request</a>
        <a class="navbar-link" href="{% url 'purchaseRequests:summary' %}">Summary</a>
        <a class="navbar-link right-aligned-nav" id="github-link" href="https://github.com/MLavrentyev/TeamManager">
            <i class="fab fa-github"></i>
        </a>
        <a class="navbar-link right-aligned-nav" id="logout-link" href="{% url 'accounts:logout' %}">(Log Out)</a>
        <h1 class="navbar-link right-aligned-nav" id="navbar-user">Welcome, {{ user }}</h1>
    </div>
</header>